name: "elasticsearch"

services:
  elasticsearch:
    image: bitnami/elasticsearch:8.13.1
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    volumes:
      - /data/elasticsearch:/bitnami/elasticsearch/data
    environment:
      - ELASTICSEARCH_PASSWORD=password
      - ELASTICSEARCH_ENABLE_SECURITY=false

  kibana:
    image: bitnami/kibana:8.13.1
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    volumes:
      - /data/kibana:/bitnami
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
      - KIBANA_ELASTICSEARCH_PORT_NUMBER=9200
      - KIBANA_PASSWORD=password
