name: "mongodb"

services:
  mongodb:
    image: bitnami/mongodb:8.3.0
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=database
