name: "postgresql"

services:
  postgresql:
    image: bitnami/postgresql:16.2.0
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=database
