name: redis

services:
  redis:
    image: bitnami/redis:7.2.4
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/bitnami/redis/data
    environment:
      - REDIS_DATABASE=database
      - REDIS_PASSWORD=password
